### ISSUE TITLE
Document the need to set Property of geojson feature

### ISSUE THREAD

**Issue by functionsonly** [slovely/OverlappingFeatureSpiderfier#7]
Nice implementation.  Can you add the need to have a property of "visible" set for the geojson feature?  Otherwise the library won't spiderfy the markers.

**Comment by slovely** [comment]
You mean like this line on the readme?  😜 

![image](https://user-images.githubusercontent.com/692489/83231638-b785ac00-a183-11ea-8060-cead9f04e875.png)

Feel free to update the readme file to make it clearly if you wish (or alternatively, update the code so that it treats visible as true if it is not set at all (`undefined`).

**Comment by functionsonly** [comment]
That's rather amazing, I could have sworn I Ctrl-F'ed for visible lol.
